spring.application.name=spring-boot-angular


spring.datasource.url=jdbc:postgresql://localhost:5432/spring-boot-angular
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.sql.init.mode=always

#specifin to JWT
security.jwt.issuer=SpringSecurityExample
security.jwt.secret-key=FSmFQ0tNPt79eHKSiuaxu0Kwtie6El27XyVCPwTvlFU
security.jwt.expiry-time-in-seconds=3600
